from app.schemas import AuditReport


def render_markdown_report(report: AuditReport) -> str:
    s = report.spend_summary
    annualization_factor = 365 / s.date_range_days if s.date_range_days > 0 else 1.0

    lines = [
        "# Gradient AI Procurement Audit",
        "",
        f"**Audit ID:** {report.audit_run_id}  ",
        f"**Report ID:** {report.report_id}  ",
        f"**Generated:** {report.generated_at.strftime('%Y-%m-%d %H:%M UTC')}  ",
        f"**Confidence:** {report.confidence_score:.0%}",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        report.executive_summary,
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| **Current Annual Spend** | ${report.current_annual_spend:,.0f} |",
        f"| **Potential Annual Savings** | ${report.potential_annual_savings:,.0f} |",
        f"| **Savings Rate** | {report.savings_rate:.0%} |",
        f"| **Confidence Score** | {report.confidence_score:.0%} |",
        "",
        "---",
        "",
        "## Top Opportunities",
        "",
    ]

    if not report.top_opportunities:
        lines += [
            "No optimization opportunities were identified in this dataset. "
            "Upload a broader data sample to improve audit coverage.",
            "",
        ]
    else:
        for i, opp in enumerate(report.top_opportunities, 1):
            task_label = opp.task_type.replace("_", " ").title()
            lines += [
                f"### {i}. {task_label}",
                "",
                "| Metric | Value |",
                "|---|---|",
                f"| **Current annualized spend** | ${opp.current_annualized_spend:,.0f} |",
                f"| **Recommended model** | {opp.recommended_model} ({opp.recommended_model_group}) |",
                f"| **Estimated annual savings** | ${opp.estimated_annual_savings:,.0f} ({opp.estimated_savings_pct:.0f}% reduction) |",
                f"| **Confidence** | {opp.confidence:.0%} |",
                "",
                f"**Recommendation:** {opp.recommended_action}",
                "",
                f"**Rationale:** {opp.rationale}",
                "",
            ]

    lines += ["---", "", "## Spend Concentration", ""]
    lines.append("*This section supports the audit findings above.*")
    lines.append("")

    if s.provider_breakdown:
        lines += ["### By Provider", "", "| Provider | Annualized Spend | Share |", "|---|---|---|"]
        for provider, cost in sorted(s.provider_breakdown.items(), key=lambda x: -x[1]):
            annual = cost * annualization_factor
            pct = cost / s.total_cost * 100 if s.total_cost > 0 else 0
            lines.append(f"| {provider} | ${annual:,.0f} | {pct:.1f}% |")
        lines.append("")

    if s.model_breakdown:
        lines += ["### By Model", "", "| Model | Annualized Spend | Share |", "|---|---|---|"]
        for model, cost in sorted(s.model_breakdown.items(), key=lambda x: -x[1]):
            annual = cost * annualization_factor
            pct = cost / s.total_cost * 100 if s.total_cost > 0 else 0
            lines.append(f"| {model} | ${annual:,.0f} | {pct:.1f}% |")
        lines.append("")

    if s.top_cost_driving_task_types:
        lines += ["### By Task Type", "", "| Task Type | Annualized Spend | Share |", "|---|---|---|"]
        for item in s.top_cost_driving_task_types:
            annual = item.cost * annualization_factor
            pct = item.cost / s.total_cost * 100 if s.total_cost > 0 else 0
            lines.append(f"| {item.task_type.replace('_', ' ').title()} | ${annual:,.0f} | {pct:.1f}% |")
        lines.append("")

    lines += ["---", "", "## Risk Notes", ""]
    for note in report.risk_notes:
        category_label = note.category.replace("_", " ").title()
        lines += [
            f"**[{note.severity.upper()}] {category_label}**  ",
            note.description,
            "",
        ]

    lines += ["---", "", "## Recommended Next Actions", ""]
    for i, action in enumerate(report.recommended_next_actions, 1):
        lines.append(f"{i}. {action}")

    lines += [
        "",
        "---",
        "",
        "*Generated by Gradient AI Procurement Audit.*  ",
        "*Estimates are based on observed usage patterns and model tier analysis.*  ",
        "*Validate all recommendations through replay testing before making production changes.*",
    ]

    return "\n".join(lines)
